apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-telemeter-client
    role: alert-rules
  name: sre-telemeter-client
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-telemeter-client
    rules:
    - alert: MetricsClientSendFailingSRE
      expr: 100 * rate(metricsclient_request_send{status_code="5xx"}[5m]) / rate(metricsclient_request_send[5m]) > 14.4 * 0.1 and 100 * rate(metricsclient_request_send{status_code="5xx"}[1h]) / rate(metricsclient_request_send[1h]) > 14.4 * 0.1
      for: 5m
      labels:
        severity: critical
        namespace: openshift-monitoring
      annotations:
        description: "Telemeter client is experiencing a high error rate over the past hour"
