apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-multiwindow-multiburn
    role: alert-rules
  name: sre-multiwindow-multiburn
  namespace: openshift-monitoring
spec:
  groups:
  - name: slos
    rules:
      record: route:error_slo:percent
      labels:
        route: console
      expr: 0.5
  
  - name: multiwindow_recording_rules
    rules:
    - record: route:haproxy_route_backend_http_errors:ratio_rate5m
      expr: |2
          sum by (route)(rate(haproxy_backend_http_responses_total{code="5xx"}[5m]))
        /
          sum by (route)(rate(haproxy_backend_http_responses_total[5m]))
    - record: route:haproxy_route_backend_http_errors:ratio_rate30m
      expr: |2
          sum by (route)(rate(haproxy_backend_http_responses_total{code="5xx"}[30m]))
        /
          sum by (route)(rate(haproxy_backend_http_responses_total[30m]))
    - record: route:haproxy_route_backend_http_errors:ratio_rate1h
      expr: |2
          sum by (route)(rate(haproxy_backend_http_responses_total{code="5xx"}[1h]))
        /
          sum by (route)(rate(haproxy_backend_http_responses_total[1h]))
    - record: route:haproxy_route_backend_http_errors:ratio_rate2h
      expr: |2
          sum by (route)(rate(haproxy_backend_http_responses_total{code="5xx"}[2h]))
        /
          sum by (route)(rate(haproxy_backend_http_responses_total[2h]))
    - record: route:haproxy_route_backend_http_errors:ratio_rate6h
      expr: |2
          sum by (route)(rate(haproxy_backend_http_responses_total{code="5xx"}[6h]))
        /
          sum by (route)(rate(haproxy_backend_http_responses_total[6h]))
    - record: route:haproxy_route_backend_http_errors:ratio_rate1d
      expr: |2
          sum by (route)(rate(haproxy_backend_http_responses_total{code="5xx"}[1d]))
        /
          sum by (route)(rate(haproxy_backend_http_responses_total[1d]))
    - record: route:haproxy_route_backend_http_errors:ratio_rate3d
      expr: |2
           sum by (route)(rate(haproxy_backend_http_responses_total{code="5xx"}[3d]))
         /
           sum by (route)(rate(haproxy_backend_http_responses_total[3d]))
  
  - name: route_multiwindow_alerts
    rules:
    - alert: ErrorBudgetBurn
      expr: |2
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate1h
          > on (job)
            14.4 * route:error_slo:percent
          )
        and
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate5m
          > on (job)
            14.4 * route:error_slo:percent
          )
      for: 2m
      labels:
        router: "{{$labels.job}}"
        severity: "critical"
        long_window: "1h"
      annotations:
        summary: "a route burns its error budget very fast"
        description: "Route {{$labels.route}} has returned {{ $value | printf `%.2f` }}% errors over the last hour."
    - alert: ErrorBudgetBurn
      expr: |2
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate6h
          > on (job)
            6 * route:error_slo:percent
          )
        and
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate30m
          > on (job)
            6 * route:error_slo:percent
          )
      for: 15m
      labels:
        router: "{{$labels.job}}"
        severity: "critical"
        long_window: "6h"
      annotations:
        summary: "a route burns its error budget very fast"
        description: "Route {{$labels.route}} has returned {{ $value | printf `%.2f` }}% errors over the 6 hours."
    - alert: ErrorBudgetBurn
      expr: |2
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate1d
          > on (job)
            3 * route:error_slo:percent
          )
        and
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate2h
          > on (job)
            3 * route:error_slo:percent
          )
      for: 1h
      labels:
        router: "{{$labels.job}}"
        severity: warning
        long_window: "1d"
      annotations:
        summary: "a route burns its error budget very fast"
        description: "Route {{$labels.route}} has returned {{ $value | printf `%.2f` }}% errors over the last day."
    - alert: ErrorBudgetBurn
      expr: |2
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate3d
          > on (job)
            1 * route:error_slo:percent
          )
        and
          (
            100 * route:haproxy_route_backend_http_errors:ratio_rate6h
          > on (job)
            1 * route:error_slo:percent
          )
      for: 1h
      labels:
        router: "{{$labels.job}}"
        severity: warning
        long_window: "3d"
        namespace: "{{$labels.exported_namespace}}"
        exporter_namespace: "{{$labels.exported_namespace}}"
      annotations:
        summary: "a route burns its error budget very fast"
        description: "Route {{$labels.route}} has returned {{ $value | printf `%.2f` }}% errors over the last 3 days."
