apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-telemeter-client
    role: alert-rules
  name: sre-telemeter-client
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-telemeter-client
    rules:
    - alert: MetricsClientSendFailingSRE
      expr: sum by (job) (rate(metricsclient_request_send{status_code!="200"}[5m])) / sum by (job) (rate(metricsclient_request_send[5m])) > (6 - (1-0.90000) and sum by (job) (rate(metricsclient_request_send{status_code!="200"}[1h])) / sum by (job) (rate(metricsclient_request_send[1h])) > (6 - (1-0.90000)
      for: 5m
      labels:
        severity: critical
        namespace: openshift-monitoring
      annotations:
        description: "Telemeter client is experiencing a high error rate over the past hour"
