apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-telemeter-client
    role: alert-rules
  name: sre-telemeter-client
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-telemeter-client
    rules:
    - alert: MetricsClientSendFailingSRE
      expr: sum by (job) (rate(metricsclient_request_send{status_code!="200"}[10m])) / sum by (job) (rate(metricsclient_request_send[10m])) > (16.12 - (1-0.90000)) and sum by (job) (rate(metricsclient_request_send{status_code!="200"}[2h])) / sum by (job) (rate(metricsclient_request_send[2h])) > (16.12 - (1-0.90000))
      for: 10m
      labels:
        severity: critical
        namespace: openshift-monitoring
      annotations:
        description: "Telemeter client is experiencing a high error rate over the past hour"
