---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ClusterLogging.v1.logging.openshift.io
  name: openshift-logging
  namespace: openshift-logging
spec:
  serviceAccount:
    metadata:
      creationTimestamp: null
  targetNamespaces:
  - openshift-logging
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Elasticsearch.v1.logging.openshift.io
    olm.providedAPIs: Kibana.v1.logging.openshift.io
  name: elasticsearch
  namespace: openshift-operators-redhat
